services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/bepoisso/data/wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/bepoisso/data/wordpress_data:/var/www/wordpress
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_PWD=${WP_PWD}
      - WP_EMAIL=${WP_EMAIL}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/bepoisso/data/mariadb_data:/var/lib/mysql
    tmpfs:
      - /run/mysqld
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:
    name: wordpress_data
  mariadb_data:
    name: mariadb_data

networks:
  inception:
    name: inception
    driver: bridge
